/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Noel
 */
public class Largo extends javax.swing.JPanel {

    /**
     * Creates new form Largo
     */
    public Largo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNormal = new javax.swing.JPanel();
        jlbF1 = new javax.swing.JLabel();
        jlbF2 = new javax.swing.JLabel();
        jlbF3 = new javax.swing.JLabel();
        jlbF4 = new javax.swing.JLabel();
        jlbF5 = new javax.swing.JLabel();
        jlbF6 = new javax.swing.JLabel();
        jlbF7 = new javax.swing.JLabel();
        jlbF8 = new javax.swing.JLabel();
        jlbF10 = new javax.swing.JLabel();
        jlbF11 = new javax.swing.JLabel();
        jlbF12 = new javax.swing.JLabel();
        jlbF13 = new javax.swing.JLabel();
        jlbF14 = new javax.swing.JLabel();
        jlbF15 = new javax.swing.JLabel();
        jlbF16 = new javax.swing.JLabel();
        jlbF17 = new javax.swing.JLabel();
        jlbF18 = new javax.swing.JLabel();
        jlbF19 = new javax.swing.JLabel();
        jlbF20 = new javax.swing.JLabel();
        jlbF21 = new javax.swing.JLabel();
        jlbF22 = new javax.swing.JLabel();
        jlbF23 = new javax.swing.JLabel();
        jlbF24 = new javax.swing.JLabel();
        jlbF25 = new javax.swing.JLabel();

        pnlNormal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlNormal.setLayout(null);

        jlbF1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF1MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF1);
        jlbF1.setBounds(8, 8, 80, 80);

        jlbF2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF2MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF2);
        jlbF2.setBounds(106, 8, 80, 80);

        jlbF3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF3MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF3);
        jlbF3.setBounds(204, 8, 80, 80);

        jlbF4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF4MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF4);
        jlbF4.setBounds(302, 8, 80, 80);

        jlbF5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF5MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF5);
        jlbF5.setBounds(302, 117, 80, 80);

        jlbF6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF6MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF6);
        jlbF6.setBounds(204, 117, 80, 80);

        jlbF7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF7MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF7);
        jlbF7.setBounds(106, 117, 80, 80);

        jlbF8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF8MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF8);
        jlbF8.setBounds(8, 117, 80, 80);

        jlbF10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF10MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF10);
        jlbF10.setBounds(106, 215, 80, 80);

        jlbF11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF11MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF11);
        jlbF11.setBounds(204, 215, 80, 80);

        jlbF12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF12MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF12);
        jlbF12.setBounds(302, 215, 80, 80);

        jlbF13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF13MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF13);
        jlbF13.setBounds(302, 313, 80, 80);

        jlbF14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF14MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF14);
        jlbF14.setBounds(8, 215, 80, 80);

        jlbF15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF15MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF15);
        jlbF15.setBounds(420, 320, 80, 80);

        jlbF16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF16MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF16);
        jlbF16.setBounds(106, 313, 80, 80);

        jlbF17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF17MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF17);
        jlbF17.setBounds(204, 313, 80, 80);

        jlbF18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF18MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF18);
        jlbF18.setBounds(8, 313, 80, 80);

        jlbF19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF19MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF19);
        jlbF19.setBounds(540, 10, 80, 80);

        jlbF20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF20MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF20);
        jlbF20.setBounds(550, 320, 80, 80);

        jlbF21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF21MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF21);
        jlbF21.setBounds(420, 220, 80, 80);

        jlbF22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF22MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF22);
        jlbF22.setBounds(420, 10, 80, 80);

        jlbF23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF23MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF23);
        jlbF23.setBounds(420, 120, 80, 80);

        jlbF24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF24MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF24);
        jlbF24.setBounds(540, 120, 80, 80);

        jlbF25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbF25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbF25MouseClicked(evt);
            }
        });
        pnlNormal.add(jlbF25);
        jlbF25.setBounds(540, 220, 80, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlbF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF1MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF1.getText())) - 1);
    }//GEN-LAST:event_jlbF1MouseClicked

    private void jlbF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF2MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF2.getText())) - 1);
    }//GEN-LAST:event_jlbF2MouseClicked

    private void jlbF3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF3MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF3.getText())) - 1);
    }//GEN-LAST:event_jlbF3MouseClicked

    private void jlbF4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF4MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF4.getText())) - 1);
    }//GEN-LAST:event_jlbF4MouseClicked

    private void jlbF5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF5MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF5.getText())) - 1);
    }//GEN-LAST:event_jlbF5MouseClicked

    private void jlbF6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF6MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF6.getText())) - 1);
    }//GEN-LAST:event_jlbF6MouseClicked

    private void jlbF7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF7MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF7.getText())) - 1);
    }//GEN-LAST:event_jlbF7MouseClicked

    private void jlbF8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF8MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF8.getText())) - 1);
    }//GEN-LAST:event_jlbF8MouseClicked

    private void jlbF10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF10MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF10.getText())) - 1);
    }//GEN-LAST:event_jlbF10MouseClicked

    private void jlbF11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF11MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF11.getText())) - 1);
    }//GEN-LAST:event_jlbF11MouseClicked

    private void jlbF12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF12MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF12.getText())) - 1);
    }//GEN-LAST:event_jlbF12MouseClicked

    private void jlbF13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF13MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF13.getText())) - 1);
    }//GEN-LAST:event_jlbF13MouseClicked

    private void jlbF14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF14MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF14.getText())) - 1);
    }//GEN-LAST:event_jlbF14MouseClicked

    private void jlbF15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF15MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF15.getText())) - 1);
    }//GEN-LAST:event_jlbF15MouseClicked

    private void jlbF16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF16MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF16.getText())) - 1);
    }//GEN-LAST:event_jlbF16MouseClicked

    private void jlbF17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF17MouseClicked
        // TODO add your handling code here:
        if (jugarONo()) {
            mostrarImagen(Integer.parseInt((jlbF17.getText())) - 1);
    }//GEN-LAST:event_jlbF17MouseClicked

    private void jlbF18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbF18MouseClicked

    private void jlbF19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbF19MouseClicked

    private void jlbF20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbF20MouseClicked

    private void jlbF21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbF21MouseClicked

    private void jlbF22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbF22MouseClicked

    private void jlbF23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbF23MouseClicked

    private void jlbF24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbF24MouseClicked

    private void jlbF25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbF25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbF25MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbF1;
    private javax.swing.JLabel jlbF10;
    private javax.swing.JLabel jlbF11;
    private javax.swing.JLabel jlbF12;
    private javax.swing.JLabel jlbF13;
    private javax.swing.JLabel jlbF14;
    private javax.swing.JLabel jlbF15;
    private javax.swing.JLabel jlbF16;
    private javax.swing.JLabel jlbF17;
    private javax.swing.JLabel jlbF18;
    private javax.swing.JLabel jlbF19;
    private javax.swing.JLabel jlbF2;
    private javax.swing.JLabel jlbF20;
    private javax.swing.JLabel jlbF21;
    private javax.swing.JLabel jlbF22;
    private javax.swing.JLabel jlbF23;
    private javax.swing.JLabel jlbF24;
    private javax.swing.JLabel jlbF25;
    private javax.swing.JLabel jlbF3;
    private javax.swing.JLabel jlbF4;
    private javax.swing.JLabel jlbF5;
    private javax.swing.JLabel jlbF6;
    private javax.swing.JLabel jlbF7;
    private javax.swing.JLabel jlbF8;
    private javax.swing.JPanel pnlNormal;
    // End of variables declaration//GEN-END:variables
}
